#!/bin/bash

# Check env file
envfile=../pie2500m.env
if [ ! -e $envfile ]; then
  echo "ops $envfile is missing!"
  exit 1;
else
  source $envfile
fi

rm -fv FICJD LISTING_DIA OUT_DIA dirconv conv2dia.file
rm -fv d.${NAM_SIMU}.*.${NAM_SEG}.*_dg.des d.${NAM_SIMU}.*.${NAM_SEG}.*_dg.lfi
